@KaffeeZeit.Server_HostAddress = http://localhost:5248

GET {{KaffeeZeit.Server_HostAddress}}/coworker/
Accept: application/json

###


POST {{KaffeeZeit.Server_HostAddress}}/coworker/
Accept: application/json
Content-Type: application/json

{
  "name": "bob"
}

###

POST {{KaffeeZeit.Server_HostAddress}}/coworker/
Accept: application/json
Content-Type: application/json

{
  "name": "jim"
}

###

POST {{KaffeeZeit.Server_HostAddress}}/coworker/
Accept: application/json
Content-Type: application/json

{
  "name": "matt"
}

###

GET {{KaffeeZeit.Server_HostAddress}}/tab/
Accept: application/json

###

POST {{KaffeeZeit.Server_HostAddress}}/tab/
Accept: application/json
Content-Type:application/json

{
  "orders": [
    {
      "coworkerId": "a426f15c-23d9-45b2-9c5c-f368192d8411",
      "drinkCost": 1.00
    },
    {
      "coworkerId": "0d9d1107-a55f-4acd-8b1a-1294fc5437c5",
      "drinkCost": 2.00
    },
    {
      "coworkerId": "652ad97f-c3c9-485f-9647-cf267f61b475",
      "drinkCost": 1.50
    }
  ],
  "revision": 1
}

###

POST {{KaffeeZeit.Server_HostAddress}}/tab/pay
Accept: application/json
Content-Type:application/json

{
  "coworkerId": "e9104738-3839-4dfc-8063-a1d0717276b1",
  "overrideNext": false
}

###